# In the `schema.yaml` file, we are defining the structure of a dataset,
# specifying which columns are categorical and numerical for easier processing.
# The `drop_columns` section lists columns to be excluded, while `num_features`
# and `oh_columns` specify which columns will undergo numerical transformation and one-hot encoding, respectively.
# The `transform_columns` section outlines which numerical features will be transformed for further analysis or modeling.

# In simpler words jo chiz EDA ke bad pta chali thi un issues ko solve kerne ke liye
# schema file banayi hai

columns:
  - case_id: category
  - continent: category
  - education_of_employee: category
  - has_job_experience: category
  - requires_job_training: category
  - no_of_employees: int
  - yr_of_estab: int
  - region_of_employment: category
  - prevailing_wage: int
  - unit_of_wage: category
  - full_time_position: category
  - case_status: category

numerical_columns:
  - no_of_employees
  - prevailing_wage
  - yr_of_estab

categorical_columns:
  - case_id
  - continent
  - education_of_employee
  - has_job_experience
  - requires_job_training
  - region_of_employment
  - unit_of_wage
  - full_time_position
  - case_status

drop_columns:
  - case_id
  - yr_of_estab

# for data transformation
num_features:
  - no_of_employees
  - prevailing_wage
  - company_age

or_columns:
  - has_job_experience
  - requires_job_training
  - full_time_position
  - education_of_employee

oh_columns:
  - continent
  - unit_of_wage
  - region_of_employment

transform_columns:
  - no_of_employees
  - company_age
